Sidney-/slugtrade

- slug_trade/slug_trade/settings.py
- slug_trade/slug_trade/urls.py
- slug_trade/slug_trade_app/views.py
- slug_trade/templates/slug_trade_app/base.html
Description:
Removed the slug_trade_app route from all routes so app name will no longer show up in url
Testing:
- Click all links to make sure they are working
- Login and logout
- Go directly to these routes in url:
http://127.0.0.1:8000/home
http://127.0.0.1:8000/products
http://127.0.0.1:8000/profile
http://127.0.0.1:8000/login
> slug_trade_app removed from all routes

- slug_trade/slug_trade_app/views.py
Problem:
- When the user wasn't logged in, and they tried to go to the edit profile page, it threw a 404 error
How to test:
- Make sure you aren't logged in, then go to /edit_profile/. Make sure that you see the error page rather than a 404 error. 
- Log in and make sure you get directed to the correct page
> Bug Fix: Edit Profile 404 error when user not logged in

- slug_trade/venv_setup.sh
New functionality:
- The script venv_setup.sh now correctly installs the required modules the app.
How to test:
- Ensure that you have python3, pip, and virtualenv installed.
- In the directory slutrade/slug_trade, run the script venv_setup.sh
- Verify that there are no error messages in the script output and that the last line of output begins with "Successfully installed".
- Run the script renew_db.sh and verify that there are no errors in the output.
- Start the script start.sh and verify that the app starts.
Note: If your global python environment already has all the correct modules installed, you will not be able to verify that the virtual environment is set up correctly.
> Fixed script to set up virtualenv in repo

- slug_trade/venv_setup.sh
I noticed that running the venv_setup script outside of my virtual environment resulted in it not working, so I reverted the merge into dev and changed pip to pip3, which fixes the issue on my machine.
> changed pip to pip3

- slug_trade/slug_trade_app/management/commands/populate_db.py
Fixes:
- when populate_db is run, admin now gets an email address
- when populate_db is run, usernames are now set to the full email address
How to test:
- run renew_db.sh
- in the app, go to the endpoint "admin/"
- log in as admin (username: "admin", password: "pass1234")
- view the Users database and verify that the user "admin" has the email "admin@slugtrade.com"
- view the Users database and verify that all the regular users have email addresses for usernames
> bugfix for Issue #35: populate_db creates irregularities in the database

- slug_trade/slug_trade_app/views.py
- slug_trade/templates/slug_trade_app/profile.html
Bugfix:
- After clicking on an arbitrary user's profile, the name that appears on the navbar will no longer change. It should remain the name of the logged in user
How to test:
- Go to /users and click on a few profiles. Make sure that the info on the Profile looks correct and the name on the navbar remains the name of the user that you are logged in as
> bugfix: navbar name

- slug_trade/static/javascripts/main.js
- slug_trade/templates/slug_trade_app/edit_profile.html
New functionality:
-Browser should pop up a warning message when the user tries to leave the edit profile page without first saving their changes
- It should not pop up if the user hasn't changed anything or if the form is submitted
How to test:
1) Go to /edit_profile, don't change any fields and make sure you can navigate away from the page without getting a warning
2) Change one or more fields then try to navigate away from the page without saving. Make sure that you get a warning message
3) Try submitting the page as normal with some changes to make sure that it behaves normally and no warning comes up
Notes:
- Customizable warning messages are no longer supported by major browsers. I could not find a better way to create this effect with a custom message :(
> Edit profile warning message

- slug_trade/static/css/styles.css
Bug:
- When the user was not scrolled up at the top of the screen, the dropdown under Welcome, {user}! did not work correctly
How to test:
1) Log in to an account
2) Make try hovering over the welcome messages in different scroll positions on the screen
3) Make sure you can also click the links
> Bugfix: Landing Dropdown

- slug_trade/slug_trade_app/forms.py
Bug:
- On Emma's machine (firefox only), some of the text fields overflowed their container
How to test:
- Load up firefox and go to the signup page and make sure it looks normal
- Decrease the width of the browser and make sure it still looks normal
Note:
- The only way I could reproduce this bug on my computer was by decreasing the screen size. I was able to fix it from my point of view, but it wasn't completely testable for me since I'm not running Ubuntu
> Bugfix: Overflowing Text Fields

- slug_trade/templates/slug_trade_app/login.html
Bug:
- No error message was shown when the user entered a wrong username/password on login
How to test:
- Enter a wrong username/password combo :P
> Bugfix: Login Error Message

- slug_trade/slug_trade_app/management/commands/populate_db.py
after pulling branch and renewing db do the following:
In the appropriate directory call python manage.py shell
This will load the Django database specific prompt
Enter The following in the python prompt to view the counters for all of the items
from slug_trade_app.models import Item
for item in Item.objects.all():
print(item.bid_counter)
You should see a range of randomly chosen numbers printed out.
> Add popularity counter db

- slug_trade/slug_trade_app/forms.py
- slug_trade/slug_trade_app/views.py
- slug_trade/static/css/styles.css
- slug_trade/static/javascripts/main.js
- slug_trade/templates/slug_trade_app/add_closet_item.html
- Updated method of adding photos to closet items
- Increased the width of the add closet items panel (small css change)
How to test:
- Add and delete a whole bunch of items in a whole bunch of different ways!!
- Make sure these properties are always upheld:
- Items with the ? are always on the far right side of the container (never in the middle or left)
- You cannot add another photo selector without first selecting images for all of your current file selectors
- You can submit variable amounts of images (after adding and deleting a bunch)
- When you try to submit without adding at least 1 photo, you get an alert
- Images always appear in the middle of the containers and scale in a way that makes sense
Notes:
- There are a lot of weird edge cases that I found while …
> Add closet item refactor

- slug_trade/slug_trade_app/models.py
Item field category is now initialized with the correct character length requirement (8) appears to have fixed bug.
> altered schema for max-length

- slug_trade/slug_trade_app/views.py
- slug_trade/static/css/styles.css
- slug_trade/static/javascripts/main.js
- slug_trade/templates/slug_trade_app/products.html
New functionality:
- Pagination controls are more styled
- Pagination controls show a maximum of 9 pages at once
- Added << and >> buttons to navigate forward or backward 5 pages
- Fixed a bug where changing pages would get rid of applied filters
How to test:
- go to /products
- Make sure the pagination controls look good
- Change pages by clicking on the number and the <, > buttons
- Go into views.py and alter line 69. Change the second parameter of the function from 12 to 1. This will allow you to see what the pagination controls look like when there are more than 2 pages to display
- Make sure that the << and >> buttons work (they should move backward/forward 5 pages
- Change the 1 back to a 12 in views.py when you're finished testing
> Pagination rework

- slug_trade/templates/slug_trade_app/products.html
Change:
- Removed an unnecessary csrf token from the filtering form
How to test:
- Go to /products and filter by anything, then make sure that you don't see a csrfmiddlewaretoken parameter in the url
> removed csrf token from the products filtering form

- slug_trade/templates/slug_trade_app/profile.html
Bug that was fixed:
- Upon viewing someone's profile who had items in their wishlist, you could not see the wishlist header
How to test:
- Add items to your wishlist, switch accounts and view the profile that you were originally on. Test if you can see the wishlist header
> Bugfix: wishlist header on other people's profiles

- slug_trade/slug_trade_app/views.py
- slug_trade/templates/slug_trade_app/products.html
Bug:
- The products page was very empty when there were no query results
Fix:
- I added a message when there are no items to show
How to test:
- Filter by "Cash with items on top" and "Electronics". Make sure you see the message.
- Make sure you don't see the message when there are items to show
> bugfix: empty products page

- slug_trade/slug_trade_app/models.py
- slug_trade/static/css/styles.css
- slug_trade/templates/slug_trade_app/products.html
- slug_trade/templates/slug_trade_app/profile.html
Goal of this PR:
- Make the text underneath the item titles in the closet and the products page more sensible. Before, the purpose of the text was unclear. On your profile, many items said "Make an Offer", which implies that you can click on that text to make an offer on your own item. This PR aims to make the text explain what the trader wants for that item. For example, if they want cash only, it will show the price, and if they want to trade for only items, it will say Offers Welcome. 
Changes:
- I changed the names of the categories (in models.py) like such:
- Cash with items on top --> Cash and Items
- Trades only --> Items Only
- Cash Only --> Cash Only (remained the same)
- Free --> Free (remained the same)
How to test:
- Go to the profile page and make sure that the following …
> Item text rework

- slug_trade/runserver.sh
- slug_trade/slug_trade_app/management/commands/populate_db.py
- slug_trade/slug_trade_app/models.py
- slug_trade/slug_trade_app/views.py
___
After renewing the database:
go to the route /products; there should be at least one item of each transaction type
items only, free, cash only
Attempting to manually access a route for a transaction with an item id that should not be processed by that route should not be allow, and an httpresponse will redirect the user to the home page
> Trade categories fix

- slug_trade/slug_trade_app/forms.py
- slug_trade/static/css/styles.css
- slug_trade/templates/slug_trade_app/header-footer/navigation.html
- slug_trade/templates/slug_trade_app/item_details.html
- slug_trade/templates/slug_trade_app/transaction.html
**Overview**
- Worked out styling for offers page for cash items, trades, and free
**Test**
- The Functionality should still be working from the offer PR
- Go to offers page from a cash item. You should see a styled preview of the item the user is bidding on. A styled cash form with a dollar sign on the left. The dollar sign should not be touching the numbers. You should also see a styled text area for the comment and a submit button. 
- Go to the offers page from a trade item. You should see a styled preview of the item the user is bidding on. You should see a styled grid of items from your closet. You should see a styled text area for comment with a submit button
- Go to the offers page from a free item. You should see a styled preview of the item the user is bidding on. You should a …
> Finished styling for offers page

- slug_trade/static/css/styles.css
- slug_trade/static/javascripts/main.js
- slug_trade/templates/slug_trade_app/products.html
- The Order By drop down on the products page has been moved next to the pagination controls
- The page should auto filter each time you change the value of the drop down
How to test:
- Go to /products
- Make sure the order by drop down is to the left of the pagination controls and looks good
- Change the value of the drop down and make sure that the page reloads with the new filter applied
- Apply some of the other filters, then change the drop down, make sure the other filters are persistent
> Order By Fix

- slug_trade/slug_trade_app/views.py
- When you are not logged in, and you click snag on an item, you are redirected to the not logged in page instead of home/products
How to test:
- Make sure you are not logged in and try to snag an item of type free, items only and cash only. Ensure that you are directed to the not logged in page for all item types
- Log back in and ensure that you can still get to the offer page from all trade types
> Bugfix: Snag Login

- slug_trade/slug_trade_app/views.py
Bug:
- When an items only offer was placed, the comments would be stored in the wrong order within the database
How to test:
- Place an items only offer (with a comment)
- Check the Offer comments table in the admin app. Ensure that the comment has the correct users.
> Bugfix: issue #124 (Item only trade comments are stored with the wrong owner)

- slug_trade/templates/slug_trade_app/profile.html
Bug:
- Clicking on closet items in the profile page does nothing
How to test:
- Click on items in your closet. Ensure that you are taken to the item details page
- Click on items in other people's closets. Ensure that you are taken to the item details page
Note: 
- There is another bug out right now that allows users to snag their own items only items)
> Bugfix: #121 (Products on other people's profiles are not clickable)

- slug_trade/static/css/styles.css
- slug_trade/templates/slug_trade_app/profile.html
**New functionality**
- Profile image no longer squishes 
- User image and data stacks on smaller screens
- Add item to closet button is restyled to match edit profile button
- Closet item images fit full width of container on larger screens
**Testing**
Button Style
- Button should have a dark gray border with a 5px radius, white background, dark gray text
- Clicking button should take you to add item page
- Hovering over the button should show white text and a dark gray background
Closet Item Style
- Expand your browser to be larger than your screen size. For any screen 13"+ the closet item's image should always be the same width of the parent wrapper/div (profile-item-image-wrapper)
Profile Image
- At all screen sizes the profile image should have proper proportions (1:1 ratio - should …
> Profile update: image width, add item button, squished profile

- slug_trade/windows_renew_db.bat
- slug_trade/windows_start.bat
- slug_trade/windows_venv_setup.bat
- Added scripts for venv_setup, renew_db and start that will work on Windows
How to Test:
- Prerequisites:
- You must be on a Windows machine
- You must have python 3.4 or higher installed on the machine
- Run the following files in the windows command prompt, verifying that they work the same as the mac/linux scripts:
- windows_venv_setup.bat
- windows_renew_db.bat
- windows_start.bat
- Notes:
- You can run these files by either double clicking them in the Windows File Explorer, or navigating to slugtrade/slug_trade, then typing in the names of the files.
- If you run the files by double clicking on them, the command prompt will close when the script is finished running
- In order to make the venv_setup script more comprehensive, I added an instruction to pip install …
> Windows scripts

- slug_trade/static/css/styles.css
- slug_trade/static/javascripts/main.js
- slug_trade/templates/slug_trade_app/transaction.html
- Instead of clicking a checkbox under each item that you want to offer (in an items only offer), you click the entire box.
How to Test:
- Make an offer on an items only item
- When you offer your closet items, make sure that you can do so by clicking anywhere on the box
- Any currently selected items will be highlighted in yellow
- Submit the offer, then check in the admin app that the correct closet items were offered
> Reworked the way you select closet items in an offer

- slug_trade/static/css/styles.css
- slug_trade/templates/slug_trade_app/add_closet_item.html
- slug_trade/templates/slug_trade_app/base.html
Bug:
- On large monitors, on pages that don't take up the entire page, the footer does not end up at the bottom
How to Test:
- Glance at all of the pages, making sure that the footer looks normal (and the rest of the page)
> Bugfix: Issue #146 (Footer misplaced on big screens)

- slug_trade/static/css/styles.css
- slug_trade/templates/slug_trade_app/transaction.html
Bug:
- On the offer page for items only items, the images are squished horizontally.
How to test:
- Go to to an items only offer page
- Check that images are no longer horizontally squished
> Bugfix: Issue #131 (Item images are squished on offer page)

- slug_trade/static/css/styles.css
- Added a shadow behind the closet items on the items only offer page
How to Test:
- Go to an items only offer
- Look at the closet items
- Ensure that they have a shadow effect behind the container
- Ensure that it looks good
> Added a shadow effect on the offer page items

- slug_trade/static/css/styles.css
Bug:
- On windows / linux on firefox, the text in the dropdowns on the add closet item page was cut off
How to Test:
- Go to the add closet item page on a windows or linux machine using firefox
- Ensure that the dropdown menus look normal
> Bugfix: Issue #158 (Dropdowns on add closet items are cut off)

- slug_trade/slug_trade_app/forms.py
- slug_trade/static/css/styles.css
Bug:
- On the add closet item, edit closet item and make an offer pages, textareas have courier font
How to Test:
- Go to the add closet item page and make sure that the description field doesn't use courier font
- Go to the editcloset item page and make sure that the description field doesn't use courier font
- Go to the offer pages of all types (Cash, Items Only, Free) and make sure the comment field doesn't use courier font
> Bugfix: Issue #160 (Textareas have courier font)

- slug_trade/static/css/styles.css
- slug_trade/templates/slug_trade_app/transaction.html
Change:
- On the Make an Offer page, I moved the title of each closet item below the picture and removed some un-needed padding
How to Test:
- Go to the offer page of an items only offer. Ensure that the closet items look good.
> Moved the title below the picture on the offer page items
